import type { Metadata } from "next";
import LocalFont from "next/font/local"
import "./globals.css";

const ddin = LocalFont({
  src: '../font/d-din/D-DIN.otf',
  variable: '--font-ddin',
})

const ddinBold = LocalFont({
  src: '../font/d-din/D-DIN-Bold.otf',
  variable: '--font-ddinBold'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ddin.variable} ${ddinBold.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
