import type { Metadata } from "next";
import LocalFont from "next/font/local"
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const ddin = LocalFont({
  src: '../fonts/d-din/D-DIN.otf',
  variable: '--font-ddin',
})

const ddinBold = LocalFont({
  src: '../fonts/d-din/D-DIN-Bold.otf',
  variable: '--font-ddinBold'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=
    {`${ddin.variable} ${ddinBold.variable}`}
    >
      <body className="relative">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
      
    </html>
  );
}
